name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://postgres:password@postgres:5432/OneLLM
  POSTGRES: postgres://postgres:password@postgres:5432/OneLLM
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DB: OneLLM
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Wait for PostgreSQL
        run: |
          for i in {1..10}; do
            pg_isready -h postgres -p 5432 && break
            echo "Waiting for PostgreSQL..."
            sleep 3
          done

      - name: Run database migrations (if any)
        run: cargo run --bin migrate || true

      - name: Run tests from testing.rs 
        run: cargo test --bin oneAI-backend --verbose

      - name: Cargo check
        run: cargo check --bin oneAI-backend --verbose
